[project]
name = "rubberducky"
version = "0.1.0"
description = "Malicious fastapi server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cryptography>=44.0.2",
    "fastapi[standard]>=0.115.12",
    "requests>=2.21.0",
]
