[project]
name = "rubberducky"
version = "0.1.0"
description = "Malicious fastapi server"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "requests>=2.32.3",
]
